

export const cards=[{
    src:'/images/seoul.jpg',
    name:'서울',
    engName:'seoul',
    videoConstant:0.03,
    intro:['과거와 현재가 공존하는 도시','서울을 즐겨보세요'],
    place:[{title:'경복궁',
            detail:'조선 왕조 제일의 법궁으로, 북으로는 북악산, 정문인 광화문 앞으로는 넓은 육조거리(지금의 세종로)가 펼쳐져, 왕도인 한양의 도시계획의 중심이 되었던 문화재입니다. 도심 속 펼쳐진 고궁의 분위기를 만끽해보세요',
            img:'gyeongbokgung.jpg',
            },
            {title:'N서울타워',
            detail:'도심 속 우뚝 솟아 있는 N서울타워입니다. 서울 시내 전 지역에서 바라보이는 타워에서 아름다운 서울의 전경을 감상하세요.',
            img:'NSeoulTower.jpg',
            },
            {title:'반포한강공원',
            detail:'반포대교 남단 부근에 위치한 한강공원으로, 달빛무지개분수, 세빛둥둥섬 등 다양한 볼거리와 한강의 아름다운 풍경을 자랑합니다. 한강의 평화로운 분위기를 즐기고 싶다면 반포한강공원에 방문해보세요.',
            img:'banpohanriver.png',
            },
            {title:'광장시장',
            detail:'종로에 위치한 서울 최대 규모의 재래시장입니다.정겨운 분위기와 다양한 먹거리를 즐기고 싶다면 지금 광장시장을 방문해 보세요',
            img:'gwangjangmarket.jpg',
            },
   ],
   isReady:true,

    },
    {
        src:'/images/busan.jpeg',
        name:'부산',
        engName:'busan',
        videoConstant:0.5,
        intro:['대한민국 제 2의 심장','부산을 즐겨보세요'],
        place:[{title:'해운대',
                detail:'조선 왕조 제일의 법궁으로, 북으로는 북악산, 정문인 광화문 앞으로는 넓은 육조거리(지금의 세종로)가 펼쳐져, 왕도인 한양의 도시계획의 중심이 되었던 문화재입니다. 도심 속 펼쳐진 고궁의 분위기를 만끽해보세요',
                img:'gyeongbokgung.jpg',
                },
                {title:'부산2',
                detail:'도심 속 우뚝 솟아 있는 N서울타워입니다. 서울 시내 전 지역에서 바라보이는 타워에서 아름다운 서울의 전경을 감상하세요.',
                img:'NSeoulTower.jpg',
                },
                {title:'부산3',
                detail:'반포대교 남단 부근에 위치한 한강공원으로, 달빛무지개분수, 세빛둥둥섬 등 다양한 볼거리와 한강의 아름다운 풍경을 자랑합니다. 한강의 평화로운 분위기를 즐기고 싶다면 반포한강공원에 방문해보세요.',
                img:'banpohanriver.png',
                },
                {title:'부산4',
                detail:'종로에 위치한 서울 최대 규모의 재래시장입니다.정겨운 분위기와 다양한 먹거리를 즐기고 싶다면 지금 광장시장을 방문해 보세요',
                img:'gwangjangmarket.jpg',
                },
        ],
        isReady:false,

    },
    {
        src:'/images/jeju.jpeg',
        name:'제주',
        engName:'jeju',
        videoConstant:0.2,
        intro:['천혜의 자연환경을 품은 땅','제주를 즐겨보세요'],
        place:[{title:'성산일출봉',
            detail:'마그마가 물속에서 분출하면서 만들어진 수성화산체로, 해가 뜨는 모습이 장관이라 하여 일출봉이라는 이름이 붙은 장소입니다. 유네스코 세계자연유산에 지정된 아름다운 성산일출봉에 방문해보세요.',
            img:'ilchulbong.jpeg',
            },
            {title:'월정리해변',
            detail:"'달이 머문다'뜻의 이름을 가진 월정리에 위치한 해변입니다. 서정적인 풍경과 에메랄드 빛 바다가 그리는 한폭의 아름다운 경치를 만끽해 보세요.",
            img:'woljeongli.jpeg',
            },
            {title:'카멜리아힐',
            detail:'수많은 동백꽃을 만날 수 있는 동백 수목원 입니다. 아기자기한 포토 스팟에서 인생 사진을 남기고 싶다면 카멜리아힐에 방문해 보세요.',
            img:'camellia.jpeg',
            },
            {title:'한라산국립공원',
            detail:'태고의 신비를 그대로 간직한 산, 한라산입니다. 섬 중앙에 우뚝 솟은 웅장한 자태와 ㅜㅁ철 따라 바뀌는 형형색색의 자연경관을 온몸으로 느껴보세요.',
            img:'halla.jpeg',
            },
        ],
        isReady:true,
    },
    {
        src:'/images/yeosu.jpg',
        name:'여수',
        engName:'yeosu',
        isReady:false,
    },
    {
        src:'/images/gangneung.jpg',
        name:'강릉',
        engName:'gangneung',
        isReady:false,
    },
    {
        src:'/images/jeonju.jpg',
        name:'전주',
        engName:'jeonju',
        isReady:false,
    },
    {
        src:'/images/gyeongju.jpg',
        name:'경주',
        engName:'gyeongju',
        isReady:false,
    }
];

